Java Build Aspects extractors
ashkboos/MavenSecrets pull request #9
Opened 2023-05-03 13:04 UTC by St33lPhoenix

Add extractor for Maven compiler plugin configuration Add extractor for Java module detection
Add extractor for Java version extraction
Add extractor for parent artifacts
Refactor existing code

2023-05-03 13:51 UTC, cryocz requested changes

2023-05-03 13:51 UTC, cryocz commented on analyzer/src/main/java/nl/tudelft/mavensecrets/extractors/JavaVersionExtractor.java
> +                if (stream.read(buf) != buf.length || buf[0] != 0xCA || buf[1] != 0xFE || buf[2] != 0xBA || buf[3] != 0xBE) {
Bytes are sign extended and therefore do not match

2023-05-03 13:51 UTC, cryocz commented on analyzer/src/main/java/nl/tudelft/mavensecrets/extractors/JavaVersionExtractor.java
> +            new Field("java_version_class_major", "BIT(16)"),
Postgres cannot coerce a byte array into `BIT(n)` apparently

2023-05-03 13:54 UTC, St33lPhoenix commented on analyzer/src/main/java/nl/tudelft/mavensecrets/extractors/JavaVersionExtractor.java
> +            new Field("java_version_class_major", "BIT(16)"),
What is the correct type for fixed-size binary data then? PostgreSQL dialect does not support `BINARY(n)`.

2023-05-03 13:59 UTC, St33lPhoenix commented on analyzer/src/main/java/nl/tudelft/mavensecrets/extractors/JavaVersionExtractor.java
> +                if (stream.read(buf) != buf.length || buf[0] != 0xCA || buf[1] != 0xFE || buf[2] != 0xBA || buf[3] != 0xBE) {
See latest commit.

2023-05-03 14:27 UTC, cryocz commented on analyzer/src/main/java/nl/tudelft/mavensecrets/extractors/JavaVersionExtractor.java
> +            new Field("java_version_class_major", "BIT(16)"),
Yeaaah, you either have to convert it into an `INT32` or use `BYTEA`

2023-05-03 14:30 UTC, St33lPhoenix commented on analyzer/src/main/java/nl/tudelft/mavensecrets/extractors/JavaVersionExtractor.java
> +            new Field("java_version_class_major", "BIT(16)"),
See latest commit.

2023-05-03 14:38 UTC, cryocz approved these changes
Looks good to me

2023-05-04 10:47 UTC, Vel1khan commented
LGTM

2023-05-04 10:47 UTC, merged